services:
  ollama-server:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: ollama/ollama
    networks:
      - my-net
    ports:
      - 11434:11434
    container_name: ollama-server
    volumes:
       - ./ollama/pull-model.sh:/pull-model.sh     # Make sure path is correct
    entrypoint: ["sh", "/pull-model.sh"]  # Use absolute path in container

networks:
  my-net:
    driver: bridge